INSERT INTO Rooms (Capacity, fk_VenueID) VALUES ('25',(SELECT VenueID FROM Venue WHERE VenueID='1'))
INSERT INTO Rooms (Capacity, fk_VenueID) VALUES ('55',(SELECT VenueID FROM Venue WHERE VenueID='1'))
INSERT INTO Rooms (Capacity, fk_VenueID) VALUES ('98',(SELECT VenueID FROM Venue WHERE VenueID='1'))
INSERT INTO Rooms (Capacity, fk_VenueID) VALUES ('76',(SELECT VenueID FROM Venue WHERE VenueID='1'))
INSERT INTO Rooms (Capacity, fk_VenueID) VALUES ('46',(SELECT VenueID FROM Venue WHERE VenueID='1'))